# Generated by Django 4.2.6 on 2023-11-28 21:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clapsUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(max_length=120)),
                ('latit', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('longit', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_teatro', models.BooleanField(default=False)),
                ('is_commonUser', models.BooleanField(default=True)),
                ('is_company', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id_show', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('sinopsis', models.CharField(max_length=900)),
                ('trailer_url', models.CharField(max_length=200)),
                ('fecha_show', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=10, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
                ('teatro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teatro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='critica',
            fields=[
                ('id_crit', models.AutoField(primary_key=True, serialize=False)),
                ('cuerpo_crit', models.CharField(max_length=900)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
                ('id_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_show', to='accounts.show')),
            ],
        ),
    ]
