# Generated by Django 4.2.6 on 2023-10-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clapsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('direction', models.CharField(max_length=120)),
                ('latit', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longit', models.DecimalField(decimal_places=10, max_digits=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_teatro', models.BooleanField(default=False)),
                ('is_commonUser', models.BooleanField(default=True)),
                ('is_hall', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
