# Generated by Django 4.2.6 on 2023-10-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clapsuser',
            name='latit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='clapsuser',
            name='longit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15),
        ),
    ]
