# Generated by Django 4.2.6 on 2023-12-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image2_url',
            field=models.CharField(default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='image_url',
            field=models.CharField(default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='trailer_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
