# Generated by Django 4.2.6 on 2023-10-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clapsuser_latit_alter_clapsuser_longit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clapsuser',
            name='latit',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='clapsuser',
            name='longit',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
