# Generated by Django 4.2.6 on 2023-10-22 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clapsuser_latit_alter_clapsuser_longit'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('sinopsis', models.CharField(max_length=900)),
                ('trailer_url', models.URLField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to=settings.AUTH_USER_MODEL)),
                ('teatro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teatro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
